In [2]:
import pandas as pd

data_dir = '/home/leiyu/scratch/cma_hallucination/data/'
max_len_prompt = 32

lama_completion_df = pd.read_csv(
        data_dir + 'lama/gpt2-xl-completion-prompt-{}.csv'.format(max_len_prompt))

In [6]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

lama_completion_df.head(50)

,prompt,true object,LM completion
0,The A605 road is a main road in the English counties of,Northamptonshire,"The A605 road is a main road in the English counties of Cumbria,"
1,The A605 road is a main road in the English counties of,Northamptonshire,"The A605 road is a main road in the English counties of Cumbria,"
2,It connects the Leicestershire town of Market Harborough and the A6 with the,Northamptonshire,It connects the Leicestershire town of Market Harborough and the A6 with the ute route between the two
3,It connects the Leicestershire town of Market Harborough and the A6 with the,Northamptonshire,It connects the Leicestershire town of Market Harborough and the A6 with the ute route between the two
4,It connects the Leicestershire town of Market Harborough and the A6 with the,Northamptonshire,It connects the Leicestershire town of Market Harborough and the A6 with the ute route between the two
5,"The Lindenberg Peninsula is a peninsula on the eastern coast of Kupreanof Island, Alexander Archipelago in southeastern",Alaska,"The Lindenberg Peninsula is a peninsula on the eastern coast of Kupreanof Island, Alexander Archipelago in southeastern ʻŌhi"
6,between Kupreanof Island to the west and the,Alaska,between Kupreanof Island to the west and the ʻŌhi
7,Frederick Sound (also called Prince Frederick Sound or Prince Frederick's Sound) is a passage of water in the Alexander Archipelago in southeastern,Alaska,Frederick Sound (also called Prince Frederick Sound or Prince Frederick's Sound) is a passage of water in the Alexander Archipelago in southeastern ʻŌhi
8,Kupreanof Island is an island in the Alexander Archipelago in southeastern,Alaska,Kupreanof Island is an island in the Alexander Archipelago in southeastern ʻŌhi
9,Kupreanof Island is an island in the Alexander Archipelago in southeastern,Alaska,Kupreanof Island is an island in the Alexander Archipelago in southeastern ʻŌhi
10,"Imlay is a census-designated place (CDP) in Pershing County,",Nevada,"Imlay is a census-designated place (CDP) in Pershing County, ʻŌhi"
11,"State Route 400 (SR 400) is a state highway in central Pershing County,",Nevada,"State Route 400 (SR 400) is a state highway in central Pershing County, California, United States"
12,"Mill City is an unincorporated community in Pershing County,",Nevada,"Mill City is an unincorporated community in Pershing County, Ohio, United States"
13,"The highway is almost entirely within Washoe County but does for a brief time enter Pershing County,",Nevada,"The highway is almost entirely within Washoe County but does for a brief time enter Pershing County, which is in the"
14,"The highway is almost entirely within Washoe County but does for a brief time enter Pershing County,",Nevada,"The highway is almost entirely within Washoe County but does for a brief time enter Pershing County, which is in the"
15,"State Route 858 (SR 858) was a short state highway in Pershing County,",Nevada,"State Route 858 (SR 858) was a short state highway in Pershing County, California."
16,"State Route 860 (SR 860) is a state highway in southern Pershing County,",Nevada,"State Route 860 (SR 860) is a state highway in southern Pershing County, California, United States"
17,"State Route 859 (SR 859) is a former state highway in Pershing County,",Nevada,"State Route 859 (SR 859) is a former state highway in Pershing County, __________.\n\n"
18,"State Route 859 (SR 859) is a former state highway in Pershing County,",Nevada,"State Route 859 (SR 859) is a former state highway in Pershing County, __________.\n\n"
19,"State Route 856 (SR 856) is a state highway in Pershing County,",Nevada,"State Route 856 (SR 856) is a state highway in Pershing County, Nevada, United"
20,"State Route 854 (SR 854) is a state highway in Pershing County,",Nevada,"State Route 854 (SR 854) is a state highway in Pershing County, Nevada, United"
21,"State Route 398 (SR 398) is a state highway in Pershing County,",Nevada,"State Route 398 (SR 398) is a state highway in Pershing County, California, United States"
22,"State Route 398 (SR 398) is a state highway in Pershing County,",Nevada,"State Route 398 (SR 398) is a state highway in Pershing County, California, United States"
23,"Star City was a silver-mining boom town in Pershing County,",Nevada,"Star City was a silver-mining boom town in Pershing County, where the population was"
24,"Star City was a silver-mining boom town in Pershing County,",Nevada,"Star City was a silver-mining boom town in Pershing County, where the population was"
25,"In 1907, he moved to Rosebud in Pershing County,",Nevada,"In 1907, he moved to Rosebud in Pershing County, where he built a"
26,"Etna is a former townsite, now a ghost town, in Pershing County,",Nevada,"Etna is a former townsite, now a ghost town, in Pershing County, Ohio."
27,"Etna is a former townsite, now a ghost town, in Pershing County,",Nevada,"Etna is a former townsite, now a ghost town, in Pershing County, Ohio."
28,"Vernon, was a small mining town, now a ghost town, located in Pershing County,",Nevada,"Vernon, was a small mining town, now a ghost town, located in Pershing County, Utah."
29,"Vernon, was a small mining town, now a ghost town, located in Pershing County,",Nevada,"Vernon, was a small mining town, now a ghost town, located in Pershing County, Utah."
30,"Vernon, was a small mining town, now a ghost town, located in Pershing County,",Nevada,"Vernon, was a small mining town, now a ghost town, located in Pershing County, Utah."
31,"Rochester, Nevada, was a silver-mining town in Pershing County,",Nevada,"Rochester, Nevada, was a silver-mining town in Pershing County, which is in the"
32,"Rochester, Nevada, was a silver-mining town in Pershing County,",Nevada,"Rochester, Nevada, was a silver-mining town in Pershing County, which is in the"
33,"The Selenite Range is a mountain range in western Pershing County,",Nevada,"The Selenite Range is a mountain range in western Pershing County, California, United States"
34,"The Seven Troughs Range is a mountain range in western Pershing County,",Nevada,"The Seven Troughs Range is a mountain range in western Pershing County, California, United States"
35,"The Blue Wing Mountains are a mountain range in west central Pershing County,",Nevada,"The Blue Wing Mountains are a mountain range in west central Pershing County, Ohio. The Blue"
36,"The East Range is a mountain range in the Great Basin region, located in Pershing County,",Nevada,"The East Range is a mountain range in the Great Basin region, located in Pershing County, Nevada. The"
37,"The Eugene Mountains are a mountain range in Pershing County,",Nevada,"The Eugene Mountains are a mountain range in Pershing County, Oregon, United States"
38,"The Antelope Range is a mountain range in Pershing County,",Nevada,"The Antelope Range is a mountain range in Pershing County, California, United States"
39,"The Hannan Range is a mountain range in Pershing County,",Nevada,"The Hannan Range is a mountain range in Pershing County, Nevada, United"
40,"State Route 396 (SR 396) is a state highway in Pershing County,",Nevada,"State Route 396 (SR 396) is a state highway in Pershing County, California, United States"
41,"State Route 396 (SR 396) is a state highway in Pershing County,",Nevada,"State Route 396 (SR 396) is a state highway in Pershing County, California, United States"
42,"The Majuba Mountains are a mountain range in Pershing County,",Nevada,"The Majuba Mountains are a mountain range in Pershing County, Utah."
43,"The Poker Brown Mountains are a mountain range in Pershing County,",Nevada,"The Poker Brown Mountains are a mountain range in Pershing County, Nevada, United"
44,"The Sheephead Mountains are a mountain range in Pershing County,",Nevada,"The Sheephead Mountains are a mountain range in Pershing County, Nevada, United"
45,"The Sahwave Mountains are a mountain range in Pershing County,",Nevada,"The Sahwave Mountains are a mountain range in Pershing County, California, United States"
46,"The Trinity Range is a mountain range in Pershing County,",Nevada,"The Trinity Range is a mountain range in Pershing County, Nevada, United"
47,"The Tobin Range is a mountain range in eastern Pershing County,",Nevada,"The Tobin Range is a mountain range in eastern Pershing County, California, USA."
48,"State Route 399 (SR 399) is an 18.18-mile (29.26 km) state highway in Pershing County,",Nevada,"State Route 399 (SR 399) is an 18.18-mile (29.26 km) state highway in Pershing County, ʻŌhi"
49,Lovelock Correctional Center is a,Nevada,Lovelock Correctional Center is a medium-security prison

In [20]:
from tqdm import tqdm
import spacy

nlp = spacy.load("en_core_web_sm")
lm_completions = []

for i, row in tqdm(lama_completion_df.iterrows(), total=lama_completion_df.shape[0]):
    try:
        prompt = row['prompt']
        completion = row['LM completion']

        lm_completions.append(completion.split(prompt)[1].strip())
    except Exception as e:
        lm_completions.append('')

100%|██████████| 100000/100000 [00:05<00:00, 19269.05it/s]

In [24]:
# detect entities generated by gpt

detected_ents = []
for doc in nlp.pipe(lm_completions, disable=["tok2vec", "tagger", "parser", "attribute_ruler", "lemmatizer"]):
    detected_ents.append([(ent.text, ent.label_) for ent in doc.ents])

In [31]:
# classify detected generated entities based on their factualities
# if gpt fails to generate the ground-truth missing object and instead predicts 
# some other entities, mark these examples as hallucinations
# if gpt correctly generates a missing object, mark the example as factual

detected_ent_types = []
n_factual = 0
n_hallucinate = 0

for i, row in tqdm(lama_completion_df.iterrows(), total=lama_completion_df.shape[0]):
    if detected_ents[i]:
        if lm_completions[i] != '' and not row['true object'] in lm_completions[i]:
            detected_ent_types.append('hallucinated')
            n_hallucinate += 1
        elif lm_completions[i] != '' and row['true object'] in lm_completions[i]:
            detected_ent_types.append('factual')
            n_factual += 1
        else:
            detected_ent_types.append('NA')
    else:
        detected_ent_types.append('NA')

100%|██████████| 100000/100000 [00:04<00:00, 23604.60it/s]

In [32]:
n_factual

13701

In [33]:
n_hallucinate

39896

In [34]:
len(detected_ent_types)

100000

In [35]:
lama_completion_df['detected entities in completion'] = detected_ents
lama_completion_df['detected entities types'] = detected_ent_types

In [39]:
# collect all mentions of detected entities into a pandas df

detected_ent_df = {
    'lama dataset idx': [],
    'entity name': [],
    'entity factuality': []
}

for i in tqdm(range(len(detected_ents))):
    if detected_ent_types[i] != 'NA':
        for ent, _ in detected_ents[i]:
            detected_ent_df['lama dataset idx'].append(i)
            detected_ent_df['entity name'].append(ent)
            if lama_completion_df['true object'][i] == ent and detected_ent_types[i] == 'factual':
                detected_ent_df['entity factuality'].append('factual')
            else:
                detected_ent_df['entity factuality'].append('hallucination')

100%|██████████| 100000/100000 [00:00<00:00, 208819.16it/s]

In [40]:
detected_ent_df = pd.DataFrame(detected_ent_df)
detected_ent_df

       lama dataset idx       entity name entity factuality
0                     2               two     hallucination
1                     3               two     hallucination
2                     4               two     hallucination
3                    11        California     hallucination
4                    11     United States     hallucination
...                 ...               ...               ...
60339             99990           Ireland     hallucination
60340             99991  House of Commons     hallucination
60341             99993                 1     hallucination
60342             99995              ʻU.S     hallucination
60343             99996                 1     hallucination

[60344 rows x 3 columns]

In [43]:
ent_factuality_type_count_df = detected_ent_df.groupby(['entity name']).agg({
    'entity factuality': lambda x: len(set(x))
}).reset_index()

In [46]:
# entities with both factual and hallucinated generations (call them target entities)

ent_factuality_type_count_df.loc[
    ent_factuality_type_count_df['entity factuality'] > 1
].reset_index()

     index    entity name  entity factuality
0      575    Afghanistan                  2
1      576         Africa                  2
2      643        Alabama                  2
3      648         Alaska                  2
4      658        Alberta                  2
5      663        Algeria                  2
6      699      Amsterdam                  2
7      769      Argentina                  2
8      775       Arkansas                  2
9      779       Armenian                  2
10     805           Asia                  2
11     818         Athens                  2
12     820        Atlanta                  2
13     830      Australia                  2
14     834        Austria                  2
15     858     Azerbaijan                  2
16     994           Baku                  2
17    1020      Baltimore                  2
18    1037        Bangkok                  2
19    1046      Barcelona                  2
20    1092        Beijing                  2
21    1100        Belarus                  2
22    1110        Belgium                  2
23    1111       Belgrade                  2
24    1136         Berlin                  2
25    1175          Bihar                  2
26    1190     Birmingham                  2
27    1260         Boston                  2
28    1278         Brazil                  2
29    1305       Brooklyn                  2
30    1316      Bucharest                  2
31    1326       Budapest                  2
32    1341       Bulgaria                  2
33    1553          Cairo                  2
34    1557        Calgary                  2
35    1559     California                  2
36    1563       Cambodia                  2
37    1567      Cambridge                  2
38    1572         Canada                  2
39    1583         Cannes                  2
40    1597        Cardiff                  2
41    1610     Casablanca                  2
42    1617        Catalan                  2
43    1619      Catalonia                  2
44    1718        Chicago                  2
45    1721          Chile                  2
46    1728        Chinese                  2
47    1736      Christian                  2
48    1738   Christianity                  2
49    1785      Cleveland                  2
50    1802        Cologne                  2
51    1803       Colombia                  2
52    1805       Colorado                  2
53    1830    Connecticut                  2
54    1870       Croatian                  2
55    1874           Cuba                  2
56    1890          Czech                  2
57    2041        Denmark                  2
58    2050        Detroit                  2
59    2059          Dhaka                  2
60    2109        Dresden                  2
61    2113          Dubai                  2
62    2114         Dublin                  2
63    2137          Dutch                  2
64    2214      Edinburgh                  2
65    2219          Egypt                  2
66    2244        England                  2
67    2245        English                  2
68    2266          Essex                  2
69    2271        Estonia                  2
70    2279         Europe                  2
71    2401        Finland                  2
72    2403        Finnish                  2
73    2442        Florida                  2
74    2455         France                  2
75    2462         French                  2
76    2602         Geneva                  2
77    2615         German                  2
78    2620        Germany                  2
79    2630          Ghana                  2
80    2662        Glasgow                  2
81    2728         Greece                  2
82    2730          Greek                  2
83    2732      Greenland                  2
84    2742    Guadalajara                  2
85    2761         Guinea                  2
86    2762        Gujarat                  2
87    2841          Haiti                  2
88    2882        Haryana                  2
89    2906         Hebrew                  2
90    2917       Helsinki                  2
91    2951          Hindi                  2
92    2953       Hinduism                  2
93    2976       Honduras                  2
94    2995        Houston                  2
95    3010        Hungary                  2
96    3148       Illinois                  2
97    3157          India                  2
98    3165      Indonesia                  2
99    3166     Indonesian                  2
100   3184           Iowa                  2
101   3187           Iran                  2
102   3195           Iraq                  2
103   3199        Ireland                  2
104   3200          Irish                  2
105   3211          Islam                  2
106   3219         Israel                  2
107   3226       Istanbul                  2
108   3229        Italian                  2
109   3231          Italy                  2
110   3290        Jakarta                  2
111   3320          Japan                  2
112   3322       Japanese                  2
113   3337      Jerusalem                  2
114   3391        Judaism                  2
115   3557          Kabul                  2
116   3666        Karachi                  2
117   3731       Kentucky                  2
118   3732          Kenya                  2
119   3733         Kerala                  2
120   3802          Khmer                  2
121   3955         Kosovo                  2
122   4252          Latin                  2
123   4277          Leeds                  2
124   4286        Leipzig                  2
125   4330      Lithuania                  2
126   4364         London                  2
127   4380      Louisiana                  2
128   4542         Madrid                  2
129   4571       Malaysia                  2
130   4576           Mali                  2
131   4580          Malta                  2
132   4581        Maltese                  2
133   4587     Manchester                  2
134   4599       Manitoba                  2
135   4625           Mari                  2
136   4637       Maryland                  2
137   4648  Massachusetts                  2
138   4688      Melbourne                  2
139   4713         Mexico                  2
140   4722          Miami                  2
141   4734       Michigan                  2
142   4752          Milan                  2
143   4764    Minneapolis                  2
144   4765      Minnesota                  2
145   4766          Minsk                  2
146   4774       Missouri                  2
147   4815        Montana                  2
148   4824       Montreal                  2
149   4839        Morocco                  2
150   4842         Moscow                  2
151   4881         Mumbai                  2
152   4883         Munich                  2
153   5193          Nepal                  2
154   5196         Nepali                  2
155   5201    Netherlands                  2
156   5203         Nevada                  2
157   5224        Newport                  2
158   5238        Nigeria                  2
159   5300         Norway                  2
160   5357           Ohio                  2
161   5363       Oklahoma                  2
162   5390        Ontario                  2
163   5395         Oregon                  2
164   5413         Ottawa                  2
165   5536       Pakistan                  2
166   5575          Paris                  2
167   5615          Pearl                  2
168   5622   Pennsylvania                  2
169   5630        Persian                  2
170   5632           Peru                  2
171   5638   Philadelphia                  2
172   5643    Philippines                  2
173   5668     Pittsburgh                  2
174   5683         Poland                  2
175   5686         Polish                  2
176   5702       Portugal                  2
177   5703     Portuguese                  2
178   5747        Punjabi                  2
179   5799          Qatar                  2
180   5813         Quebec                  2
181   5831     Queensland                  2
182   6023           Riga                  2
183   6067        Romania                  2
184   6068       Romanian                  2
185   6073           Rome                  2
186   6120         Russia                  2
187   6121        Russian                  2
188   6402   Saskatchewan                  2
189   6414       Scotland                  2
190   6420        Seattle                  2
191   6443          Seoul                  2
192   6450         Serbia                  2
193   6451        Serbian                  2
194   6498       Shanghai                  2
195   6567      Singapore                  2
196   6594         Slovak                  2
197   6660    Southampton                  2
198   6673          Spain                  2
199   6675        Spanish                  2
200   6739      Stockholm                  2
201   6748          Sudan                  2
202   6800         Sweden                  2
203   6802        Swedish                  2
204   6809    Switzerland                  2
205   6810         Sydney                  2
206   6814          Syria                  2
207   6917         Taiwan                  2
208   6931          Tamil                  2
209   6982         Tehran                  2
210   6994      Tennessee                  2
211   7004          Texas                  2
212   7008       Thailand                  2
213   7140        Tibetan                  2
214   7164          Tokyo                  2
215   7179        Toronto                  2
216   7237         Turkey                  2
217   7371        Ukraine                  2
218   7372      Ukrainian                  2
219   7411           Urdu                  2
220   7416           Utah                  2
221   7423     Uzbekistan                  2
222   7517      Venezuela                  2
223   7518         Venice                  2
224   7524        Vermont                  2
225   7530       Victoria                  2
226   7535         Vienna                  2
227   7538        Vietnam                  2
228   7550       Virginia                  2
229   7634          Wales                  2
230   7647         Warsaw                  2
231   7705      Wisconsin                  2
232   7725        Wyoming                  2
233   7777          Yemen                  2
234   7780        Yerevan                  2
235   7817         Zagreb                  2

In [53]:


target_ents = set(ent_factuality_type_count_df.loc[
    ent_factuality_type_count_df['entity factuality'] > 1
]['entity name'])

# how many examples contain factual target entities?
n_target_completions_factual = len(detected_ent_df.loc[
    (detected_ent_df['entity name'].isin(target_ents)) &\
    (detected_ent_df['entity factuality'] == 'factual')
]['lama dataset idx'])

# how many examples contain hallucinated target entities?
n_target_completions_hallucinate = len(detected_ent_df.loc[
    (detected_ent_df['entity name'].isin(target_ents)) &\
    (detected_ent_df['entity factuality'] == 'hallucination')
]['lama dataset idx'])

In [54]:
n_target_completions_factual

12761

In [55]:
n_target_completions_hallucinate

15246

In [56]:
len(target_ents)

236